name: Build and Push Docker Image

on:
  push:
    branches:
      - staging
      - dev  # Trigger on pushes to the development branch
    tags:
      - "v*.*.*"
      - "v*.*.*-alpha"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="development"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}:$TAG \
            --push .